server:
  port: 9999

spring:
  #数据库相关配置
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  #redis
  redis:
    database: 5
    password: 123456
    port: 15818
    host: localhost
    #开启redis监听key过期事件
    keyEventExpired: true

logging:
  level:
    root: info
    com.demo: debug

swagger:
  host: localhost:9999
