spring:
  profiles: #使用的配置文件
    active: dev
  application:
    name: demo-api
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#服务端口
server:
  port: 9999
  #异常处理的controller路径, 所有没有处理的异常最后会走到对应的controller中
  error:
    path: /custom/error


#mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
#  #多租户的配置
#  tenant:


response-wrap:
  ignored:
    urls: #返回值处理路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /csrf
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /encryption
      - /images/**


#API文档相关配置
knife4j:
  enable: true
  setting:
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: demo例子 @2021
